### ISSUE TITLE
FOR CONTRIBUTORS

### ISSUE THREAD

**Issue by flash76** [Elementanium/shine#3]
# For contributors

This section will be updated regularly as new help is required

### Repository Curation

Who wants to be a repository curator?!  
If you want to, you can.  
Start by:

1. Forking this repository
2. Go into `scripts/ruby/` and duplicate `TEMPLATE.rb`
3. Follow instructions in the duplicate of `TEMPLATE.rb`
4. Submit a pull request with the edited software

**Comment by LickTheCheese** [comment]
might i recommend putting this in the `wiki`?

**Comment by flash76** [comment]
Yes, I should have done that.
The other stuff was _stupid_, which is why I deleted it.
